### ISSUE TITLE
Add a way to reliably determine whether a `Receiver` is also a `Subscriber`

### ISSUE THREAD

**Issue by philiprodrigues** [DUNE-DAQ/ipm#48]
In nwqueueadapters we have generic code that has to work with a `Receiver`-type ipm connection and a `Subscriber`-type ipm connection. Subscribers need a subscription to receive any messages, so nwqa needs to determine whether the ipm connection it holds is capable of subscribing. We don't have a type field available, and `ZmqReceiverImpl` derives from both `Receiver` and `Subscriber` for both types of connection, so a `dynamic_cast<Subscriber>` will always succeed (but the attempt to subscribe will later fail if the connection is actually `Receiver`).

I've put a hacky check on plugin type name in nwqa for the moment, but we should think up something more elegant for the long term

**Comment by eflumerf** [comment]
I think this is more of a failure of ZmqReceiverImpl than anything else, and it should not even try to do a subscribe if it isn't in subscriber mode.
