### ISSUE TITLE
Write integration tests for the 0MQ implementations of the interface

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/ipm#5]
@eflumerf @philiprodrigues With (1) Eric's eflumerf/ZmqPubSub branch pulled into develop, and (2) a workable system now available with which to send commands to plugins (*), we should write integration tests so we can test simple communications between instances of the classes in this package. Probably the best starting point for describing what to do comes from the following excerpt from an email Eric sent myself and Phil back on Nov. 2:
```
Here's my thoughts for a good set of integration tests, ideally using scripts to make them semi-automatic (i.e. “Press any key to configure…”)
1-to-1 Sender/Receiver
1-to-Many (2-3) Sender/Receiver (Push/Pull 0MQ sockets should automatically round-robin to the Receivers)
1-to-1 Publisher/Subscriber
1-to-Many (2-3) Publisher/Subscriber
1-to-0 Publisher/Subscriber (Verify that Publisher continues)
```

(*) See the recent updates to the "Running" section of https://github.com/DUNE-DAQ/appfwk/wiki/Compiling-and-running-under-v1.2.1 for more on this

**Comment by philiprodrigues** [comment]
This looks like the right set of tests to me. Do we have a good setup in the app framework/daq-buildtools to run tests like this that will span multiple processes?

**Comment by jcfreeman2** [comment]
Perhaps you can elaborate? At least at first blush, it seems like for a given test we could just write a bash script which launches different daq_application processes, e.g., one containing a sender plugin and another containing a receiver plugin, to take the first of Eric's examples.

**Comment by philiprodrigues** [comment]
I was thinking of "support" from the build system to get bash scripts like the ones you mention installed in the same directory as other tests (and maybe automatically run the same way other tests are?), but thinking about it some more, it's fine to just write the scripts and run them manually for the moment - certainly good enough for making a v1 release.

**Comment by jcfreeman2** [comment]
See README.md for how to run integration tests
